{{- if .Values.route.http.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "common.names.fullname" . }}-http
spec:
  host: {{ .Values.route.http.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "common.names.fullname" . }}
{{- end }}
