{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "list-keep-front.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "list-keep-front.fullname" . }}
{{- end }}
